-- 0027_attachments.sql
-- Chat attachments: one row per uploaded file (GH-187).
--
-- The file itself lives on the attachments volume at
-- <attachments_root>/<org_id>/<id> (admino.organizations.ATTACHMENTS_ROOT);
-- the row holds its metadata only. id is generated by the application before
-- the file is written (it names the file), so it has no default.
--
-- - chat_id / owner_user_id: the chat that holds the file and its owner. The
--   composite foreign key (chat_id, org_id, owner_user_id) -> chats (id,
--   org_id, owner_user_id) makes an attachment of another org's chat, or one
--   whose owner isn't the chat's owner, impossible; chats gains the matching
--   UNIQUE key. It cascades, so deleting a user (their chats) or purging an
--   org removes the rows. That is the only path from users to attachments.
-- - message_id: the user message that carried the file, NULL until it is sent
--   (an unsent file older than 24 hours is an orphan the GC removes).
-- - filename: the sanitized original name (1 to 255 characters, no control
--   character, no path separator). Never logged, never on a platform route.
-- - kind: the type detected from the content, never from the name.
-- - size_bytes: 1 byte to 500 MiB (the platform maximum of max_file_size_mb).
-- - status: uploaded -> processing -> ready | failed; failure_reason is a
--   reason code, set exactly when the status is failed.
-- - page_count: set by processing when the file has pages (#188).
-- - deleted_at: the trash (a trashed chat trashes its files; restore and
--   purge are #194).
--
-- The CHECKs mirror the Pydantic bounds (admino.models AttachmentSummary).
--
-- The audit action catalog grows by file.upload: audit_events_action_check is
-- replaced. No audit event is changed.
--
-- Grants: the runtime role gets SELECT, INSERT and DELETE (the orphan GC) on
-- attachments, and UPDATE on exactly the columns the application writes:
-- message_id (sending), status, failure_reason, page_count, updated_at
-- (processing) and deleted_at (the trash).

ALTER TABLE chats ADD CONSTRAINT chats_id_org_owner_key UNIQUE (id, org_id, owner_user_id);

CREATE TABLE attachments (
    id             UUID        PRIMARY KEY,
    org_id         UUID        NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    chat_id        UUID        NOT NULL,
    owner_user_id  UUID        NOT NULL,
    message_id     UUID        REFERENCES chat_messages (id) ON DELETE CASCADE,
    filename       TEXT        NOT NULL
        CONSTRAINT attachments_filename_check
        CHECK (char_length(filename) BETWEEN 1 AND 255 AND filename !~ '[[:cntrl:]/\\]'),
    kind           TEXT        NOT NULL
        CONSTRAINT attachments_kind_check
        CHECK (kind IN ('pdf', 'docx', 'xlsx', 'csv', 'txt', 'md', 'png', 'jpeg', 'webp')),
    size_bytes     BIGINT      NOT NULL
        CONSTRAINT attachments_size_bytes_check CHECK (size_bytes BETWEEN 1 AND 524288000),
    status         TEXT        NOT NULL DEFAULT 'uploaded'
        CONSTRAINT attachments_status_check
        CHECK (status IN ('uploaded', 'processing', 'ready', 'failed')),
    failure_reason TEXT
        CONSTRAINT attachments_failure_reason_check
        CHECK ((status = 'failed') = (failure_reason IS NOT NULL)
               AND (failure_reason IS NULL OR failure_reason ~ '^[a-z][a-z0-9_]{0,63}$')),
    page_count     INTEGER
        CONSTRAINT attachments_page_count_check CHECK (page_count IS NULL OR page_count >= 0),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at     TIMESTAMPTZ,
    CONSTRAINT attachments_chat_fkey FOREIGN KEY (chat_id, org_id, owner_user_id)
        REFERENCES chats (id, org_id, owner_user_id) ON DELETE CASCADE
);
CREATE INDEX attachments_org_size_idx ON attachments (org_id) INCLUDE (size_bytes);
CREATE INDEX attachments_chat_idx ON attachments (chat_id, org_id, owner_user_id);
CREATE INDEX attachments_message_idx ON attachments (message_id) WHERE message_id IS NOT NULL;
CREATE INDEX attachments_unsent_idx ON attachments (created_at) WHERE message_id IS NULL;
CREATE INDEX attachments_pending_idx ON attachments (created_at)
    WHERE status IN ('uploaded', 'processing');

GRANT SELECT, INSERT, DELETE ON attachments TO admino_app;
GRANT UPDATE (message_id, status, failure_reason, page_count, updated_at, deleted_at)
    ON attachments TO admino_app;

ALTER TABLE audit_events DROP CONSTRAINT audit_events_action_check;

ALTER TABLE audit_events ADD CONSTRAINT audit_events_action_check CHECK (action IN (
    'login.success', 'login.failure', 'login.lockout',
    'password_reset.request', 'password_reset.complete', 'password.change',
    'session.revoke', 'session.force_logout',
    'invitation.create', 'invitation.revoke', 'invitation.accept', 'invitation.resend',
    'invitation.refuse',
    'user.role_change', 'user.activate', 'user.deactivate', 'user.delete',
    'user.profile_change',
    'project.share', 'project.unshare', 'project.member_role_change', 'project.transfer',
    'project.delete', 'project.restore', 'chat.delete', 'chat.restore',
    'file.upload', 'file.delete', 'file.restore', 'project.admin_access', 'export.create',
    'org.settings_change', 'org.create', 'org.limits_change', 'org.deactivate',
    'org.reactivate', 'org.deletion_schedule', 'org.deletion_cancel', 'org.purge',
    'org.residency_change', 'platform.settings_change', 'model.registry_change',
    'breakglass.start', 'breakglass.end', 'tool.call', 'audit.purge',
    'org.permission_change', 'org.permission_promote', 'org.permission_promote_cancel',
    'org.permission_demote'
));
